apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis 
  namespace: ecom-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command: [  "sh", "-c", "exec redis-server --requirepass \"$REDIS_PASSWORD\"" ]
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: redis_password
          valueFrom:
            secretKeyRef:
              name: cart-secret
              key: password
        



