apiVersion: v1 
kind: Service
metadata:
  name: redis-service
  namespace: ecom-shop
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
  sessionAffinity: None
