# use admin
# db.auth("admin", "Pass*123")
# Shared logging config
x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  mongodb:
    restart: unless-stopped
    image: mongo:4.2.24
    ports:
      - "27017:27017"
    networks:
      - ecom-shop
    environment: &mongo_env
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Pass*123
      MONGO_INITDB_DATABASE: e-commerce
    volumes:
      - ./mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    logging: *logging

  redis:
    restart: unless-stopped
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - ecom-shop
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
    logging: *logging

  elasticsearch:
    restart: unless-stopped
    image: elasticsearch:8.2.3
    ports:
      - "9200:9200"
    networks:
      - ecom-shop
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: Pass*123
      # xpack.security.enabled: "false"
    logging: *logging

  cart:
    # restart: unless-stopped
    depends_on:
      - redis
    image: arvindpdige/cart:v1
    ports:
      - "8085:8085"
    networks:
      - ecom-shop
    logging: *logging
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: Pass*123

  product:
    restart: unless-stopped
    depends_on:
      - mongodb
      - cart
      - users
      - search
    command: [ "sh", "-c", "echo 'Waiting for MongoDB...'; sleep 10; npm start" ]
    image: arvindpdige/products:v1
    ports:
      - "5001:5001"
    networks:
      - ecom-shop
    logging: *logging
    environment:
      MONGO_URI: "mongodb://admin:Pass*123@mongodb:27017/e-commerce?authSource=admin"
      DATABASE: "e-commerce"
    

  store:
    # restart: unless-stopped
    depends_on:
      - cart
      - product
    image: arvindpdige/store:v1
    ports:
      - "80:80"
    networks:
      - ecom-shop
    logging: *logging

  users:
    # restart: unless-stopped
    image: arvindpdige/users:v1
    ports:
      - "9090:9090"
    networks:
      - ecom-shop
    logging: *logging

  search:
    # restart: unless-stopped
    depends_on:
      - elasticsearch
    image: arvindpdige/search:v1
    ports:
      - "4000:4000"
    networks:
      - ecom-shop
    logging: *logging
    environment:
      discovery.type: "single-node"
      ELASTIC_URL: "http://elasticsearch:9200"
      ELASTIC_USER_NAME: "elastic"
      ELASTIC_PASSWORD: "Pass*123"
      ELASTIC_APIKEY: ""

networks:
  ecom-shop:
    driver: bridge
