version: "3.8"

# Shared logging config
x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
extra_hosts:
  - "host.docker.internal:${HOST_IP}"

services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - ecom-shop
    environment: &mongo_env
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Pass@123#
      DATABASE: e-commerce
    volumes:
      - ./mongo_data:/data/db
    logging: *logging

  redis:
    restart: unless-stopped
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - ecom-shop
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
    logging: *logging

  elasticsearch:
    restart: unless-stopped
    image: elasticsearch:8.2.3
    ports:
      - "9200:9200"
    networks:
      - ecom-shop
    environment:
      discovery.type: single-node
      # xpack.security.enabled: "false"
    logging: *logging

  cart-cna-microservice:
    restart: unless-stopped
    depends_on:
      - redis
    build: ./cart-cna-microservice
    ports:
      - "8080:8080"
    networks:
      - ecom-shop
    logging: *logging
    environment:
      SPRING_REDIS_HOST: "host.docker.internal"
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: "${REDIS_PASSWORD}"

  products-cna-microservice:
    restart: unless-stopped
    depends_on:
      - mongodb
    build: ./products-cna-microservice
    ports:
      - "8081:8081"
    networks:
      - ecom-shop
    logging: *logging
    environment:
      <<: *mongo_env
      DATABASE: "e-commerce"

  store-ui:
    restart: unless-stopped
    depends_on:
      - cart-cna-microservice
      - products-cna-microservice
    build: ./store-ui
    ports:
      - "80:80"
    networks:
      - ecom-shop
    logging: *logging

  users-cna-microservice:
    restart: unless-stopped
    build: ./users-cna-microservice
    ports:
      - "9090:9090"
    networks:
      - ecom-shop
    logging: *logging

  search-cna-microservice:
    restart: unless-stopped
    depends_on:
      - elasticsearch
    build: ./search-cna-microservice
    ports:
      - "4000:4000"
    networks:
      - ecom-shop
    logging: *logging
    environment:
      discovery.type: "single-node"
      ELASTIC_URL: "http://host.docker.internal:32200"
      ELASTIC_USER_NAME: ""
      ELASTIC_PASSWORD: ""
      ELASTIC_APIKEY: ""

networks:
  ecom-shop:
    driver: bridge
