apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart 
  namespace: ecom-shop
spec:
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      replicas: 2
      containers:
      - name: cart
        image: arvindpdige/cart:${TAG}
        ports:
        - containerPort: 8085
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: redis_password
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        



