apiVersion: v1 
kind: Service
metadata:
  name: cart-service
  namespace: ecom-shop
spec:
  selector:
    app: cart
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8085
  type: ClusterIP
  sessionAffinity: None
