apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  template:
    spec:
      containers:
        - name: cart
          image: arvindpdige/cart:<+pipeline.variables.TAG>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  template:
    spec:
      containers:
        - name: products
          image: arvindpdige/products:<+pipeline.variables.TAG>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  template:
    spec:
      containers:
        - name: search
          image: arvindpdige/search:<+pipeline.variables.TAG>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  template:
    spec:
      containers:
        - name: store
          image: arvindpdige/store:<+pipeline.variables.TAG>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  template:
    spec:
      containers:
        - name: users
          image: arvindpdige/users:<+pipeline.variables.TAG>
