apiVersion: v1
kind: Service 
metadata:
  name: app-service 
  namespace: ecom-shop
spec:
  selector:
    app: store  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: 30080
  type: LoadBalancer
  