apiVersion: v1 
kind: Service
metadata:
  name: users-service
  namespace: ecom-shop
spec:
  selector:
    app: users
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: ClusterIP
  sessionAffinity: None
