apiVersion: v1 
kind: Service
metadata:
  name: products-service
  namespace: ecom-shop
spec:
  selector:
    app: products
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
  sessionAffinity: None
