pipeline:
  name: cart test
  identifier: cart_test
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubarvind
        build: <+input>
  stages:
    - stage:
        name: cart test
        identifier: cart_test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    connectorRef: dockerhubarvind
                    repo: arvindpdige/cart
                    shell: Sh
                    command: |-
                      sudo apt install gradle -y
                      gradle -v
                      which gradle
                      sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin 
                      cd cart-cna-microservice/
                      docker --version
                      docker build -t arvindpdige/cart:v6 .
                      docker push arvindpdige/cart:v6
              - step:
                  type: BuildAndPushDockerRegistry
                  name: CartBuildAndPushDocker
                  identifier: BuildAndPushDockerRegistry_0
                  spec:
                    connectorRef: dockerhubarvind
                    repo: arvindpdige/cart
                    tags:
                      - v6
                    caching: true
                    dockerfile: /harness/cart-cna-microservice/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: ProductBuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhubarvind
                    repo: arvindpdige/products
                    tags:
                      - v6
                    caching: true
                    dockerfile: /harness/products-cna-microservice/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: StoreBuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry_2
                  spec:
                    connectorRef: dockerhubarvind
                    repo: arvindpdige/store
                    tags:
                      - v6
                    caching: true
                    dockerfile: /harness/store-ui/Dockerfile
