pipeline:
  name: cart test
  identifier: cart_test
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubarvind
        build: <+input>
  stages:
    - stage:
        name: cart test
        identifier: cart_test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerhubarvind
                    image: eclipse-temurin:17-jdk
                    shell: Sh
                    command: |-
                      java --version
                      gradle -v
                      which gradle
                      ls -lrth
                      cd cart-cna-microservice/
                      ls -ltrh
                      ./gradle build -x test
                    imagePullPolicy: IfNotPresent
              - step:
                  type: BuildAndPushDockerRegistry
                  name: CartBuildAndPushDocker
                  identifier: BuildAndPushDockerRegistry_0
                  spec:
                    connectorRef: dockerhubarvind
                    repo: arvindpdige/cart
                    tags:
                      - v6
                    caching: true
                    dockerfile: /harness/cart-cna-microservice/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: ProductBuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhubarvind
                    repo: arvindpdige/products
                    tags:
                      - v6
                    caching: true
                    dockerfile: /harness/products-cna-microservice/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: StoreBuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry_2
                  spec:
                    connectorRef: dockerhubarvind
                    repo: arvindpdige/store
                    tags:
                      - v6
                    caching: true
                    dockerfile: /harness/store-ui/Dockerfile
