pipeline:
  name: e-comm
  identifier: ecomm
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubarvind
        repoName: https://github.com/arvindpdige/E-Commerse-Project.git
        build: <+input>
        prCloneStrategy: MergeCommit
        sparseCheckout: []
  stages:
    - stage:
        name: E-comm-build
        identifier: Ecommbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      cd products-cna-microservice/
                      npm install
                  description: Build Cart
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhubarvind
                    repo: arvindpdige/products
                    tags:
                      - v6
                    caching: true
                    dockerfile: /harness/products-cna-microservice/Dockerfile
