pipeline:
  name: e-comm
  identifier: ecomm
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubarvind
        repoName: https://github.com/arvindpdige/E-Commerse-Project.git
        build: <+input>
        prCloneStrategy: MergeCommit
        sparseCheckout: []
  stages:
    - stage:
        name: E-comm-build
        identifier: Ecommbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      cd products-cna-microservice/
                      npm install
                  description: Build Cart
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhubarvind
                    repo: arvindpdige/products
                    tags:
                      - v6
                    caching: true
                    dockerfile: /harness/products-cna-microservice/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_2
                  identifier: BuildAndPushDockerRegistry_2
                  spec:
                    connectorRef: dockerhubarvind
                    repo: arvindpdige/store
                    tags:
                      - v6
                    caching: true
                    dockerfile: /harness/store-ui/Dockerfile
    - stage:
        name: delete
        identifier: delete
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          set -euo pipefail
                          # Download kubectl (adjust version as needed)
                          curl -L "https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl" -o kubectl
                          chmod +x kubectl
                          mv kubectl /usr/local/bin/
                          export KUBECONFIG=${HARNESS_KUBE_CONFIG_PATH}
                          kubectl version --client
                          # Example command
                          kubectl get pods -n ecom-shop
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
