apiVersion: v1 
kind: Service
metadata:
  name: store-service
  namespace: ecom-shop
spec:
  selector:
    app: store
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
  sessionAffinity: None
