apiVersion: v1
kind: Secret
metadata:
  name: search-secret
  namespace: ecom-shop
data:
  elastic_url: aHR0cDovL2VsYXN0aWNzZWFyY2g6OTIwMAo=
  elastic_user_name: ZWxhc3RpYwo=
  elastic_password: UGFzcyoxMjMK
type: Opaque

 
  
