apiVersion: v1 
kind: Service
metadata:
  name: search-service
  namespace: ecom-shop
spec:
  selector:
    app: search
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: ClusterIP
  sessionAffinity: None
